/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    container: {
      center: true,
      padding: { DEFAULT: '1rem', sm: '1.5rem', lg: '2rem' },
    },
    extend: {
      colors: {
        airforce: {
          blue: '#5D8AA8',
          navy: '#1D213C',
          sky: '#BAE2EE',
          skyLight: '#D7EFF6',
          skySoft: '#E4F6FB',
          steel: '#BBCAD7',
          steelDeep: '#526F86',
          black: '#131313',
          cyan: '#00D4FA',
          gold: '#FFD707',
          honey: '#E7AB33',
          saffron: '#FF671F',
          green: '#046A38',
          brown: '#8A6742',
          grayBlue: '#6B8093',
          charcoal: '#2A3946',
          white: '#FFFFFF',
          red: '#FF0000',
        },
        primary: {
          50: '#BBCAD7',
          100: '#6789A6',
          200: '#5C7C96',
          300: '#526F86',
          400: '#486276',
          500: '#3E5465',
          600: '#344656',
          700: '#2A3946',
          800: '#202C36',
          900: '#161E25',
          950: '#0E1418',
        },
        secondary: {
          DEFAULT: '#1D213C',
          light: '#34395F',
          dark: '#111426',
        },
        surface: {
          DEFAULT: '#FFFFFF',
          muted: '#F3F6F9',
          soft: '#F7FAFC',
          sky: '#E4F6FB',
        },
        text: {
          DEFAULT: '#131313',
          muted: '#455468',
          subtle: '#6D7C8F',
          inverse: '#FFFFFF',
        },
        accent: {
          DEFAULT: '#F0934B',
          dark: '#D97A2E',
          light: '#FBC998',
          saffron: '#FF671F',
          gold: '#FFD707',
        },
        success: '#046A38',
        warning: '#FF671F',
        info: '#00D4FA',
        skyback: {
          DEFAULT: '#BAE2EE',
          light: '#D7EFF6',
          soft: '#E4F6FB',
        },
        // Legacy aliases retained to avoid breaking existing components.
        AFB: '#5D8AA8',
        AFGFlagBlueBG: '#1D213C',
        AFGIndianSaffron: '#FF671F',
        AFGIndianWhite: '#FFFFFF',
        AFGIndianNavyBlue: '#06038D',
        AFGIndianGreen: '#046A38',
        navyColor: '#1D213C',
        AfricanTurquoise: '#000000',
        BrilliantYellow: '#FFD707',
        Honey: '#E7AB33',
        BrightCyan: '#00D4FA',
        DigitalRed: '#FF0000',
        OuterSpace: '#1D213C',
        SilentBlue: '#BAE2EE',
        ElegantBlack: '#131313',
      },
      fontFamily: {
        display: ['"Rajdhani"', '"Segoe UI"', 'sans-serif'],
        body: ['"Manrope"', '"Segoe UI"', 'sans-serif'],
      },
      boxShadow: {
        card: '0 24px 56px -30px rgba(17, 26, 36, 0.28)',
        soft: '0 12px 28px rgba(17, 26, 36, 0.08)',
        menu: '0 24px 52px -24px rgba(17, 26, 36, 0.26)',
      },
      borderRadius: {
        xl2: '1.25rem',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: 0, transform: 'translateY(24px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        floatY: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        radarPulse: {
          '0%': { transform: 'scale(0.92)', opacity: '0.15' },
          '50%': { transform: 'scale(1)', opacity: '0.35' },
          '100%': { transform: 'scale(1.08)', opacity: '0.1' },
        },
        spinSlow: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        fadeUp: 'fadeUp 0.7s ease forwards',
        marquee: 'marquee 30s linear infinite',
        floatY: 'floatY 4s ease-in-out infinite',
        radarPulse: 'radarPulse 6s ease-in-out infinite',
        spinSlow: 'spinSlow 18s linear infinite',
      },
    },
  },
  plugins: [],
}
